pipeline {
    agent any
    stages {
        stage("Teste") {
            steps {
                sh '''
                    ls
                    cd /var
                    ls
                    cd ~
                    ls
                '''
            }
        }
    }
}
